In [6]:
import numpy as np
#Lineage data
# The order of elements
# ['Timeframe', 'CloneID', 'ParentID', 'CellID','PositionX','PositionY','VoronoiArea','G1MarkerInVoronoiArea','ActinSegmentationArea','G1MarkerInActinSegmentationArea']

data_lineage = np.load("simulation/del-div/sample0/lineage.npy")
print(data_lineage.shape)
print(data_lineage)

(7707, 10)
[[ 0.000e+00  0.000e+00  8.930e+02 ... -9.100e+01 -3.110e+02  0.000e+00]
 [ 0.000e+00  9.000e+00  1.111e+03 ... -7.000e+00 -3.110e+02  0.000e+00]
 [ 0.000e+00  1.600e+01  6.130e+02 ... -1.000e+00 -3.110e+02  0.000e+00]
 ...
 [ 1.400e+01  1.480e+02  2.692e+03 ... -3.000e+00 -5.910e+02  0.000e+00]
 [ 1.400e+01  3.420e+02  2.471e+03 ... -2.000e+00 -5.910e+02  0.000e+00]
 [ 1.400e+01  1.660e+02  2.372e+03 ... -2.000e+00 -5.910e+02  0.000e+00]]


In [5]:
#segmentation data
data_segmentation = np.load("simulation/del-div/sample0/segmentation.npy")
print(data_segmentation.shape)

(15, 500, 500)
