In [5]:
# Copyright (c) 2021 Takaki Yamamoto
# Licensed under the Apache License, Version 2.0 (the “License”);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an “AS IS” BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Check data formats in the calculation of attribution"""

import pickle
import sys
import os
import numpy as np
#Add path to load modules

sys.path.append("../..") 
sys.path.append("..") 

try:
    sys.path.append(os.path.join(os.path.dirname(__file__), '../..'))
except:
    print("Error ignored:RunningInJupyter_RelativePath")
    
try:
    sys.path.append(os.path.join(os.path.dirname(__file__), '.'))
except:
    print("Error ignored:RunningInJupyter_RelativePath")
    
from functions import system_utility as sutil
    
    
#Const: do not change
num_feature = 6


Error ignored:RunningInJupyter_RelativePath
Error ignored:RunningInJupyter_RelativePath


In [6]:
# Paths: 
dirpath_result = "../../../analysis/3.training_attribution/simulation/del-div/feature_ZZFR/result/SP_fnum6_time4_netnorm_all_1hot_rev-FLedit_ptest0_noself1_inplane1_skip0_nullnet1_ave1_edge0_reg0-0_nullw0_even0/" #Change to feature_ZZFR

dirname_sample = "model=23_epoch=2000_hidnode=50_lr=0.000100_opt=adam_feature=feature_concat_infeats=6_penalty=1.0_shuffle=0_noself=1_drop=0.10_wd=0.000000_inplane=1_omitt0=0_border=0_ptest=0_layer=1_0/"

dirname_attribution = "attribution_n=50_MaxMacroF1/test/test_0/AllCells/0/cellID=452_reallabel=0/" 

dirname_attribution_summary = "attribution_n=50_MaxMacroF1_nnet=11/test_summary/AllCells/data/"

In [7]:
dirpath_base = dirpath_result + dirname_sample

In [8]:
# List of cell IDs in a subgraph. 
# format: 
#[[the target cell ID of the first layer(t0), neighbor1 ID(t0), neighbor2 ID(t0),... ],
#[the target cell ID of the 2nd layer(t1), neighbor1 ID(t1), neighbor2 ID(t1),...],
#...]
filepath = dirpath_base + dirname_attribution + "AllTargetCellListNoDoubling.pickle"
data = sutil.PickleLoad(filepath)
print(data)

[[1409, 259, 452, 1126, 178, 472], [1409, 259, 452, 1126, 1644, 1645, 178], [1409, 259, 452, 1126, 1644, 1645, 178], [1827, 452, 1126, 1644, 1645, 1810, 1811]]


In [9]:
# List of neiborging cell IDs in a subgraph. 
# format: 
#[[neighbor1 ID of the first layer(t0), neighbor2 ID of the first layer(t0),...],
#[neighbor1 ID of the 2nd layer(t1), neighbor2 ID of the 2nd layer(t0)(t1),...]
#...]

filepath = dirpath_base + dirname_attribution + "AllNeighborCellList.pickle"
data = sutil.PickleLoad(filepath)
print(data)

[[178, 259, 472, 1126, 1409], [178, 259, 1126, 1409, 1644, 1645], [178, 259, 1126, 1409, 1644, 1645], [1126, 1644, 1645, 1810, 1811, 1827]]


In [11]:
# List of the target cell ID in a subgraph. 
# format: [target cell of "t0",target cell of "t1",target cell of "t2"]

filepath = dirpath_base + dirname_attribution + "LineageList.pickle"
data = sutil.PickleLoad(filepath)
print(data)

[452, 452, 452, 452]


In [28]:
# Array of score f(alpha) of the subgraph. 
# [f(0),f(1/n),,f(1)]

filepath = dirpath_base + dirname_attribution + "y_score_list.pickle"
data = sutil.PickleLoad(filepath)
print(data)

[0.35310313 0.35650417 0.36043918 0.36285856 0.36497095 0.36666274
 0.36745262 0.36759359 0.36731735 0.36718437 0.36495724 0.36131868
 0.35683116 0.35285848 0.35075563 0.34964758 0.3491894  0.34880662
 0.34860426 0.34833217 0.34801814 0.34796154 0.34807754 0.34794635
 0.34726155 0.34643924 0.34562561 0.34486422 0.34423378 0.34392795
 0.34328946 0.34189934 0.340489   0.33900672 0.33792681 0.33671436
 0.33559322 0.3341819  0.33284262 0.33199227 0.33122051 0.33047232
 0.33019978 0.32969293 0.32901686 0.3284609  0.32777855 0.32647401
 0.32574019 0.32484519 0.32393494]
(51,)


In [30]:
# array of IGs of all the nodes with respect to the traget cell. 
# Note that the cells outside the subgraph have zero IGs by definition. 
filepath = dirpath_base + dirname_attribution + "IntegratedGradient_list.pickle"
data = sutil.PickleLoad(filepath)
#print(len(data))
print(data[0].shape) #t0
print(data[1].shape) #t1
print(data[2].shape) #t2
print(data[3].shape) #t3

4
torch.Size([1608, 6])
torch.Size([1704, 6])
torch.Size([1778, 6])
torch.Size([1857, 6])


In [14]:
# 1D List of relative positions of cells in a subgraph. 
# 1: the target cell, 2: the neighbor cell
# The order of cells are the 1D-flattened AllTargetCellListNoDoubling.pickle
filepath = dirpath_base + dirname_attribution + "position_all_path.pickle"
data = sutil.PickleLoad(filepath)
print(data)

[2 2 1 2 2 2 2 2 1 2 2 2 2 2 2 1 2 2 2 2 2 1 2 2 2 2 2]


In [31]:
# 1D List of time of cells in a subgraph. 
# 1: the target cell, 2: the neighbor cell
# The order of cells are the 1D-flattened AllTargetCellListNoDoubling.pickle
filepath = dirpath_base + dirname_attribution + "time_index_all.pickle"
data = sutil.PickleLoad(filepath)
print(data)
print("number of cells in the subgraph=%d"%data.shape[0])

[0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 3 3 3 3 3 3 3]
number of cells in the subnetwork=27


In [32]:
# The cell type names for 1D IG array. 
# format: ["name of feature1 of neighbor1 of in the subgraph","name of feature2 of neighbor1 of in the subgraph",,,]
# The order of cells are the same as AllTargetCellListNoDoubling.pickle. 


filepath = dirpath_base + dirname_attribution + "cell_type_name_list.pickle"
data = sutil.PickleLoad(filepath)
print(data)


# 1D array of IG of cells in a subgraph. 
# format: ["feature1 of neighbor1 of in the subgraph","feature2 of neighbor1 of in the subgraph",,,]
# The order of cells are the 1D-flattened AllTargetCellListNoDoubling.pickle


filepath = dirpath_base + dirname_attribution + "IntegratedGradient_target_1D.pickle"
data = sutil.PickleLoad(filepath)
print("number of cells in the subgraph=%d"%(int(data.shape[0]/num_feature)))
print(data)


['T0P2F0', 'T0P2F1', 'T0P2F2', 'T0P2F3', 'T0P2F4', 'T0P2F5', 'T0P2F0', 'T0P2F1', 'T0P2F2', 'T0P2F3', 'T0P2F4', 'T0P2F5', 'T0P1F0', 'T0P1F1', 'T0P1F2', 'T0P1F3', 'T0P1F4', 'T0P1F5', 'T0P2F0', 'T0P2F1', 'T0P2F2', 'T0P2F3', 'T0P2F4', 'T0P2F5', 'T0P2F0', 'T0P2F1', 'T0P2F2', 'T0P2F3', 'T0P2F4', 'T0P2F5', 'T0P2F0', 'T0P2F1', 'T0P2F2', 'T0P2F3', 'T0P2F4', 'T0P2F5', 'T1P2F0', 'T1P2F1', 'T1P2F2', 'T1P2F3', 'T1P2F4', 'T1P2F5', 'T1P2F0', 'T1P2F1', 'T1P2F2', 'T1P2F3', 'T1P2F4', 'T1P2F5', 'T1P1F0', 'T1P1F1', 'T1P1F2', 'T1P1F3', 'T1P1F4', 'T1P1F5', 'T1P2F0', 'T1P2F1', 'T1P2F2', 'T1P2F3', 'T1P2F4', 'T1P2F5', 'T1P2F0', 'T1P2F1', 'T1P2F2', 'T1P2F3', 'T1P2F4', 'T1P2F5', 'T1P2F0', 'T1P2F1', 'T1P2F2', 'T1P2F3', 'T1P2F4', 'T1P2F5', 'T1P2F0', 'T1P2F1', 'T1P2F2', 'T1P2F3', 'T1P2F4', 'T1P2F5', 'T2P2F0', 'T2P2F1', 'T2P2F2', 'T2P2F3', 'T2P2F4', 'T2P2F5', 'T2P2F0', 'T2P2F1', 'T2P2F2', 'T2P2F3', 'T2P2F4', 'T2P2F5', 'T2P1F0', 'T2P1F1', 'T2P1F2', 'T2P1F3', 'T2P1F4', 'T2P1F5', 'T2P2F0', 'T2P2F1', 'T2P2F2', 'T2P2F3',

In [33]:
# 1D array of feature values. 
# format: ["feature1 of neighbor1 of in the subgraph","feature2 of neighbor1 of in the subgraph",,,]
# The order of cells are the same as AllTargetCellListNoDoubling.pickle. 

filepath = dirpath_base + dirname_attribution + "features_target_1D.pickle"
data = sutil.PickleLoad(filepath)
print(data)
print("number of cells in the subgraph=%d"%(int(len(data)/num_feature)))

[0.         0.         1.         0.         0.         0.14119929
 0.         0.         1.         0.         0.         0.7851598
 0.         0.         1.         0.         0.         0.89524186
 0.         0.         1.         0.         0.         0.65830076
 0.         0.         1.         0.         0.         0.64340276
 0.         0.         0.         0.         1.         0.8782275
 0.         0.         1.         0.         0.         0.6529098
 0.         0.         1.         0.         0.         0.40497077
 0.         0.         1.         0.         0.         0.43182123
 0.         0.         1.         0.         0.         0.19386744
 0.         0.         1.         0.         0.         0.9890869
 0.         0.         1.         0.         0.         0.04012299
 0.         0.         1.         0.         0.         0.8160089
 0.         0.         0.         0.         1.         0.61548984
 0.         0.         0.         0.         1.         0.37714535


In [35]:
#Pooled IG, feature value and cell index (not cellID)

# List of feature values pooled in "T1P2F2", for example. 

filepath = dirpath_base  + dirname_attribution + "ForEachCellType/data/T1P2F2/features.pickle"
data = sutil.PickleLoad(filepath)
print(data)


# List of IGs pooled in "T1P2F2", for example. 

filepath = dirpath_base  + dirname_attribution + "ForEachCellType/data/T1P2F2/IG.pickle"
data = sutil.PickleLoad(filepath)
print(data)


# Index (not cell ID) of the cells in "cell_type_name_list.pickle" pooled in "T1P2F2", for example. 

filepath = dirpath_base + dirname_attribution + "ForEachCellType/data/T1P2F2/index.pickle"
data = sutil.PickleLoad(filepath)
print(data)



# if we don't have features pooled to some cell types, the list of the pooled features are null.
filepath = dirpath_base  + dirname_attribution + "ForEachCellType/data/T0P0F0/features.pickle"
data = sutil.PickleLoad(filepath)
print(data)

filepath = dirpath_base  + dirname_attribution + "ForEachCellType/data/T0P0F0/IG.pickle"
data = sutil.PickleLoad(filepath)
print(data)

filepath = dirpath_base  + dirname_attribution + "ForEachCellType/data/T0P0F0/index.pickle"
data = sutil.PickleLoad(filepath)
print(data)




[1. 1. 1. 1. 1. 1.]
[-0.01318818 -0.01203513 -0.01258469 -0.01737339 -0.01337492 -0.01470297]
[38, 44, 56, 62, 68, 74]
[]
[]
[]


In [36]:
#1D List of IGs, the cell type, relative position, time index, features for all the input subgraphs. Only information of the nodes in each subgraph is registered. 

filepath = dirpath_base + dirname_attribution_summary + "label=0_AllCells_IntegratedGradient_target_1D_all.pickle"
data = sutil.PickleLoad(filepath)
print("length = %d"%len(data))

filepath = dirpath_base + dirname_attribution_summary + "label=0_AllCells_cell_type_list_all.pickle"
data = sutil.PickleLoad(filepath)
print("length = %d"%len(data))

filepath = dirpath_base + dirname_attribution_summary + "label=0_AllCells_position_1D_all.pickle"
data = sutil.PickleLoad(filepath)
print("length = %d"%len(data))

filepath = dirpath_base + dirname_attribution_summary + "label=0_AllCells_time_index_1D_all.pickle"
data = sutil.PickleLoad(filepath)
print("length = %d"%len(data))

filepath = dirpath_base + dirname_attribution_summary + "label=0_AllCells_features_target_1D_all.pickle"
data = sutil.PickleLoad(filepath)
print("length = %d"%len(data))


length = 277278
length = 277278
length = 277278
length = 277278
length = 277278


In [38]:
#Pooled IG and feature values for all the subgraphs

filepath = dirpath_base + dirname_attribution_summary + "0/T1P2F2/IG_list_all.txt"
data = np.loadtxt(filepath)
print(data)
print("length = %d"%len(data))

[0.02063095 0.02970089 0.         ... 0.00768162 0.00804466 0.00869255]
length = 9886
